export default { 
    LOGGED_IN: 'LOGGED_IN',
    LOGGED_OUT: 'LOGGED_OUT',
    REGISTERED: 'REGISTERED',
    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_VERIFIED: 'RESET_PASSWORD_VERIFIED',
    LIST_OF_ADMINS: 'LIST_OF_ADMINS'
}